apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  namespace: home-assistant
  labels:
    app.kubernetes.io/name: mosquitto
    app.kubernetes.io/instance: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mosquitto
      app.kubernetes.io/instance: mosquitto
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mosquitto
        app.kubernetes.io/instance: mosquitto
      annotations:
        traffic.sidecar.istio.io/excludeInboundPorts: "1883"
    spec:
      containers:
        - name: mosquitto
          image: "eclipse-mosquitto:1.6.12"
          imagePullPolicy: IfNotPresent
          ports:
            - name: mqtt
              containerPort: 1883
              protocol: TCP
            - name: mqttssl
              containerPort: 8883
              protocol: TCP
            - name: mqttws
              containerPort: 9001
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 1883
          readinessProbe:
            tcpSocket:
              port: 1883
          volumeMounts:
            - name: config-volume
              mountPath: /mosquitto/config
            - name: mosquitto-data
              mountPath: /mosquitto/data/
      volumes:
        - name: config-volume
          configMap:
            name: mosquitto
        - name: mosquitto-data
          emptyDir: {}
